# Create a tempory directory to clone the code repository.
- name: Create document root
  file: 
    path: "{{ doc_root }}"
    state: directory
    mode: 0775
    recurse: yes

# Clone the application code repository. This always get the lastest code and inogre the local changes.
- name: Clone code from git repository
  git:
    repo: https://github.com/xeneta/operations-task.git
    dest: "{{ doc_root }}"
    clone: yes
    update: yes
    force: yes

- name: Create a network
  docker_network:
    name: "rates-app-network"



