# Replcae config values dynemically from variable file.
- name: Replace database name
  replace:
    path: "{{ doc_root }}/rates/config.py"
    regexp: '(?i)\"name\": \"postgres\"'
    replace: '"name": "{{ name }}"'

- name: Replace database username
  replace:
    path: "{{ doc_root }}/rates/config.py"
    regexp: '(?i)\"user\": \"postgres\"'
    replace: '"user": "{{ username }}"'

- name: Replace database hostname
  replace:
    path: "{{ doc_root }}/rates/config.py"
    regexp: '(?i)\"host\": \"localhost\"'
    replace: '"host": "{{ hostname }}"'

# Copy the docker file into app directory.
- name: Copy docker file
  template:
    src: Dockerfile
    dest: "{{ doc_root }}/rates/Dockerfile"

# Build the rates API docker image.
- name: Build docker image
  docker_image:
    name: ratesapi
    build:
      path: "{{ doc_root }}/rates/"
    source: build
    force_source: yes

# Run the rates API container in the same network where DB container exists.
- name: Run web api container
  docker_container:
    name: dev-ratesapi
    recreate: yes
    image: ratesapi:latest
    ports:
    - "3000:3000"
    networks:
    - name: "rates-app-network"
